import type { Exercise } from '@/types'

/**
 * Research-backed back exercise catalog. Grounded in EMG literature:
 * pull-ups/chin-ups out-activate lat pulldowns for the lats and demand more
 * elbow flexion (more biceps); bent-over rows shift emphasis to mid/lower
 * traps and rhomboids with the lats acting more as stabilizers; straight-arm
 * pulldowns isolate the lats with minimal biceps; conventional deadlifts hit
 * the quads and erectors harder than Romanian deadlifts, which bias the
 * hamstrings instead.
 */
export const BACK_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Pull-Up (Wide Grip, Pronated)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Chin-Up (Supinated Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'primary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Lat Pulldown (Wide Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Lat Pulldown (Close Grip, Neutral)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bent-Over Row (Overhand)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bent-Over Row (Underhand)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell One-Arm Row',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Cable Row (Close Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Chest-Supported Row (Machine)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Straight-Arm Cable Pulldown',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Deadlift (Conventional)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
      { muscle: 'Quadriceps', role: 'secondary' },
    ],
    repRangeLow: 4,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Deadlift (Sumo)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Adductors', role: 'secondary' },
    ],
    repRangeLow: 4,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Back Extension (Hyperextension)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Shrug',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Barbell',
    targetMuscles: [{ muscle: 'Trapezius (Upper)', role: 'primary' }],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Shrug',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Dumbbell',
    targetMuscles: [{ muscle: 'Trapezius (Upper)', role: 'primary' }],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Face Pull',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Meadows Row (Landmine)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Inverted Row (Bodyweight)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Renegade Row (Dumbbell)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Core (anti-rotation)', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
]
