import type { Exercise } from '@/types'

/**
 * Research-backed back exercise catalog. Grounded in EMG literature:
 * pull-ups/chin-ups out-activate lat pulldowns for the lats and demand more
 * elbow flexion (more biceps); bent-over rows shift emphasis to mid/lower
 * traps and rhomboids with the lats acting more as stabilizers; straight-arm
 * pulldowns isolate the lats with minimal biceps; conventional deadlifts hit
 * the quads and erectors harder than Romanian deadlifts, which bias the
 * hamstrings instead. Trap bar deadlifts use a neutral grip and a more
 * upright torso than conventional/sumo pulls, shifting load toward the
 * quads and easing peak erector demand; rack pulls shorten the range to the
 * lockout portion, overloading the erectors and upper back with heavier
 * weight than a full pull allows. Pendlay rows are performed dead-stop from
 * the floor each rep (no stretch reflex, more horizontal torso) versus the
 * continuous-tension bent-over row. Farmer's carries load the traps
 * isometrically under a walked load rather than through a shrugging ROM.
 * Deficit deadlifts extend the pulling range of motion to raise time under
 * tension for the erectors and hamstrings off the floor; snatch-grip
 * deadlifts widen the grip to increase torso angle and upper-back/trap
 * demand versus a conventional pull. Unilateral cable work (single-arm lat
 * pulldown) adds an anti-rotation core demand that bilateral pulldowns don't.
 */
export const BACK_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Pull-Up (Wide Grip, Pronated)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Chin-Up (Supinated Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'primary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Lat Pulldown (Wide Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Lat Pulldown (Close Grip, Neutral)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bent-Over Row (Overhand)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bent-Over Row (Underhand)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell One-Arm Row',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Cable Row (Close Grip)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Chest-Supported Row (Machine)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Straight-Arm Cable Pulldown',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Teres Major', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Deadlift (Conventional)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
      { muscle: 'Quadriceps', role: 'secondary' },
    ],
    repRangeLow: 4,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Deadlift (Sumo)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Adductors', role: 'secondary' },
    ],
    repRangeLow: 4,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Back Extension (Hyperextension)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Shrug',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Barbell',
    targetMuscles: [{ muscle: 'Trapezius (Upper)', role: 'primary' }],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Shrug',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Dumbbell',
    targetMuscles: [{ muscle: 'Trapezius (Upper)', role: 'primary' }],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Face Pull',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Meadows Row (Landmine)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Inverted Row (Bodyweight)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Renegade Row (Dumbbell)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Core (anti-rotation)', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Pendlay Row (Barbell)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Trap Bar Deadlift',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Quadriceps', role: 'secondary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Rack Pull',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 3,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Superman (Prone Back Extension)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Hyperextension (Machine)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: "Farmer's Carry",
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Trapezius (Upper)', role: 'primary' },
      { muscle: 'Forearm Flexors', role: 'secondary' },
      { muscle: 'Core', role: 'stabilizer' },
    ],
    repRangeLow: 20,
    repRangeHigh: 40,
    createdAt: Date.now(),
  },
  {
    name: 'Scapular Pull-Up',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Latissimus Dorsi', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Arm Lat Pulldown (Cable)',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lats',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary' },
      { muscle: 'Teres Major', role: 'secondary' },
      { muscle: 'Biceps Brachii', role: 'secondary' },
      { muscle: 'Core (anti-rotation)', role: 'stabilizer' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Wide-Grip Seated Cable Row',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Deficit Deadlift',
    muscleGroup: 'Back',
    muscleSubgroup: 'Lower Back',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Quadriceps', role: 'secondary' },
      { muscle: 'Latissimus Dorsi', role: 'stabilizer' },
    ],
    repRangeLow: 3,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Snatch-Grip Deadlift',
    muscleGroup: 'Back',
    muscleSubgroup: 'Traps',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Trapezius (Upper)', role: 'primary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
    ],
    repRangeLow: 3,
    repRangeHigh: 6,
    createdAt: Date.now(),
  },
  {
    name: 'Banded Pull-Apart',
    muscleGroup: 'Back',
    muscleSubgroup: 'Rhomboids',
    equipment: 'Bands',
    targetMuscles: [
      { muscle: 'Rhomboids', role: 'primary' },
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
]
