import type { Exercise } from '@/types'

/**
 * Research-backed biceps exercise catalog. Grounded in EMG literature:
 * neutral/hammer grips shift emphasis to the brachialis and brachioradialis
 * (thickness under the biceps and forearm size) rather than the biceps
 * brachii itself; incline curls stretch the long head for greater long-head
 * emphasis; preacher curls isolate the short head but only over a short arc;
 * pronated reverse curls hit the brachioradialis and forearm extensors.
 * Drag curls and overhead/"Bayesian" cable curls keep the upper arm behind
 * or in line with the torso (shoulder extension), which biases the long
 * head via a deeper stretch; wide-grip barbell curls similarly bias the
 * long head, though EMG evidence on grip-width head-bias is mixed. Chin-ups
 * are included as a compound, loaded biceps-emphasis movement (underhand
 * grip drives significant biceps EMG activation alongside the lats). A
 * close grip on a barbell/EZ-bar further biases the short head (mirroring
 * the wide-grip long-head bias above), and cable variants run at different
 * pulley heights and arm paths — low unilateral, and high/lateral for a
 * peak-contraction squeeze — to vary the resistance curve and line of pull
 * beyond what a straight- or low-pulley cable curl provides.
 */
export const BICEPS_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Curl (Straight Bar)',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Brachioradialis', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'EZ-Bar Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Brachioradialis', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Curl (Standing, Supinating)',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Brachioradialis', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Preacher Curl (Barbell/EZ-Bar)',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.8 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Preacher Curl (Dumbbell)',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.8 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hammer Curl (Dumbbell)',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.9 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.7 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cross-Body Hammer Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Brachialis', role: 'primary', activationScore: 1 },
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 0.9 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.75 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Curl (Straight Bar)',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.9 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Curl (Rope, Hammer Grip)',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.9 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.7 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Concentration Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Curl (Barbell, Pronated Grip)',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.8 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Spider Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Zottman Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 0.9 },
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 0.9 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.75 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Bicep Curl',
    muscleGroup: 'Biceps',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.7 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Drag Curl (Barbell)',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Posterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Overhead Cable Curl (Bayesian Curl)',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Wide-Grip Barbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Band Curl',
    muscleGroup: 'Biceps',
    equipment: 'Bands',
    targetMuscles: [
      { muscle: 'Biceps Brachii', role: 'primary' },
      { muscle: 'Brachialis', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Arm Cable Curl (Low Pulley)',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Close-Grip EZ-Bar Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Brachioradialis', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Incline Hammer Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Long Head)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Brachialis', role: 'primary', activationScore: 0.9 },
      { muscle: 'Brachioradialis', role: 'primary', activationScore: 0.85 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'High Cable Curl (Peak Contraction)',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Biceps Brachii (Long Head)', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Lateral Deltoid', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: "Waiter's Curl (Dumbbell)",
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Biceps Brachii (Short Head)', role: 'primary', activationScore: 1 },
      { muscle: 'Brachialis', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
