import type { Exercise } from '@/types'

/**
 * Research-backed chest exercise catalog. Grounded in EMG/biomechanics
 * literature: flat/decline pressing emphasizes the sternocostal (mid/lower)
 * pec head, incline pressing emphasizes the clavicular (upper) head,
 * dumbbells recruit more stabilizer/secondary muscle than barbells at the
 * same angle, and cables/machines hold more constant tension with less
 * stabilizer demand. Push-up angle mechanics run opposite to bench angle
 * mechanics — hands-elevated (incline push-up) biases lower chest, feet-
 * elevated (decline push-up) biases upper chest — since it's the body's
 * incline relative to gravity that matters, not the bench's. The Hex Press
 * adds a sustained horizontal-adduction (squeeze) component absent from a
 * standard dumbbell press, which EMG shows drives meaningfully higher pec
 * activation, especially at the shortened/top position — a genuinely
 * distinct stimulus, not just a grip tweak. Spoto and Larsen presses are
 * technique-focused barbell variants — pausing off the chest vs. removing
 * leg drive entirely — that change time-under-tension and stabilizer/core
 * demand without altering which pec head is primary. Unilateral variants
 * (single-arm DB press, single-arm cable crossover, archer push-up) load
 * one side at a time, driving anti-rotation core recruitment that bilateral
 * pressing doesn't demand.
 */
export const CHEST_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.2 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Incline 30°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.7 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.2 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Incline 45°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 0.9 },
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Trapezius (Upper)', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Decline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.35 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'stabilizer', activationScore: 0.2 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Incline 30°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.65 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Decline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.3 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Chest Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Chest Press (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Machine',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Smith Machine Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Smith Machine Bench Press (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Machine',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.8 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Chest Press (Standing, Flat)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.9 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (High-to-Low)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.3 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.25 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (Low-to-High)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.4 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (Mid / Flat)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Fly (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.3 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Fly (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Pec Deck / Machine Fly',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Standard)',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.45 },
      { muscle: 'Serratus Anterior', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Incline, hands elevated)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.85 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.35 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Decline, feet elevated)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.8 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Wide Grip)',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.4 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Close-Grip / Diamond)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Triceps Brachii', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.85 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dip (Chest-Focused, forward lean)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Latissimus Dorsi', role: 'stabilizer', activationScore: 0.2 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Landmine Press',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary', activationScore: 0.9 },
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Floor Press (Barbell)',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Triceps Brachii', role: 'primary', activationScore: 0.9 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.8 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Svend Press / Plate Squeeze Press',
    muscleGroup: 'Chest',
    equipment: 'Other',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.75 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Biceps Brachii', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Pullover',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Latissimus Dorsi', role: 'primary', activationScore: 0.85 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.75 },
      { muscle: 'Triceps Brachii (Long Head)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hex Press (Dumbbell Squeeze Press, Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.95 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Decline Dumbbell Fly',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.3 },
      { muscle: 'Biceps Brachii (Short Head)', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Resistance Band Chest Press (Standing)',
    muscleGroup: 'Chest',
    equipment: 'Bands',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.85 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Arm Dumbbell Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'primary', activationScore: 0.75 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Arm Cable Crossover (Standing)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Spoto Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Larsen Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Archer Push-Up',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Floor Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Triceps Brachii', role: 'primary', activationScore: 0.9 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 0.8 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Deficit Push-Up',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    movementPattern: 'horizontal_push',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.45 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
