import type { Exercise } from '@/types'

/**
 * Research-backed chest exercise catalog. Grounded in EMG/biomechanics
 * literature: flat/decline pressing emphasizes the sternocostal (mid/lower)
 * pec head, incline pressing emphasizes the clavicular (upper) head,
 * dumbbells recruit more stabilizer/secondary muscle than barbells at the
 * same angle, and cables/machines hold more constant tension with less
 * stabilizer demand. Push-up angle mechanics run opposite to bench angle
 * mechanics — hands-elevated (incline push-up) biases lower chest, feet-
 * elevated (decline push-up) biases upper chest — since it's the body's
 * incline relative to gravity that matters, not the bench's. The Hex Press
 * adds a sustained horizontal-adduction (squeeze) component absent from a
 * standard dumbbell press, which EMG shows drives meaningfully higher pec
 * activation, especially at the shortened/top position — a genuinely
 * distinct stimulus, not just a grip tweak.
 */
export const CHEST_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Incline 30°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Incline 45°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Bench Press (Decline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Incline 30°)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Bench Press (Decline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Chest Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Chest Press (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Smith Machine Bench Press (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Smith Machine Bench Press (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Chest Press (Standing, Flat)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Core (anti-rotation)', role: 'stabilizer' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (High-to-Low)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Coracobrachialis', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (Low-to-High)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Fly (Mid / Flat)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Fly (Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Fly (Incline)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Pec Deck / Machine Fly',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Standard)',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Serratus Anterior', role: 'stabilizer' },
      { muscle: 'Core', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Incline, hands elevated)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Decline, feet elevated)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Serratus Anterior', role: 'stabilizer' },
      { muscle: 'Core', role: 'stabilizer' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Wide Grip)',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Push-Up (Close-Grip / Diamond)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Triceps Brachii', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dip (Chest-Focused, forward lean)',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Landmine Press',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Upper Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Serratus Anterior', role: 'stabilizer' },
      { muscle: 'Core', role: 'stabilizer' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Floor Press (Barbell)',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Svend Press / Plate Squeeze Press',
    muscleGroup: 'Chest',
    equipment: 'Other',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Pullover',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
      { muscle: 'Triceps Brachii (long head)', role: 'secondary' },
      { muscle: 'Serratus Anterior', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hex Press (Dumbbell Squeeze Press, Flat)',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Decline Dumbbell Fly',
    muscleGroup: 'Chest',
    muscleSubgroup: 'Lower Chest',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Resistance Band Chest Press (Standing)',
    muscleGroup: 'Chest',
    equipment: 'Bands',
    targetMuscles: [
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'primary' },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'primary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Anterior Deltoid', role: 'secondary' },
      { muscle: 'Core (anti-rotation)', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
