import type { Exercise } from '@/types'

/**
 * Research-backed core exercise catalog. Grounded in EMG/ultrasound
 * literature: crunches preferentially activate the upper rectus abdominis
 * (~75% MVC) since the movement anchors at the pelvis; hanging leg raises
 * and reverse crunches activate the lower rectus abdominis and obliques
 * significantly more than crunches; plank variations with hollowing raise
 * oblique activation without changing rectus abdominis activation much.
 * Bicycle crunch and vertical leg raise variants (toes-to-bar) consistently
 * rank at or near the top of ACE/peer-reviewed EMG comparisons for combined
 * rectus/oblique recruitment; loaded carries and quadruped anti-rotation
 * work (bird dog) round out anti-lateral-flexion and anti-extension demands
 * not covered by crunch or plank patterns alone. Decline sit-ups extend
 * rectus abdominis loading through a longer range of motion than flat
 * sit-ups; unstable-surface anti-rotation work (stir-the-pot) and long-lever
 * holds (dragon flag, L-sit) add progression variants distinct from their
 * floor-based counterparts.
 */
export const CORE_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Crunch (Floor)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Crunch (Kneeling)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Crunch',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Weighted Sit-Up',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.8 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.85 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.45 },
      { muscle: 'Latissimus Dorsi', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Knee Raise',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 0.9 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.75 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Crunch',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: "Captain's Chair Leg Raise",
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.85 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Plank (Forearm)',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Transverse Abdominis', role: 'primary' },
      { muscle: 'Rectus Abdominis (Upper)', role: 'secondary' },
      { muscle: 'Obliques', role: 'secondary' },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Side Plank',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Obliques', role: 'primary' }],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Woodchopper (High-to-Low)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Woodchopper (Low-to-High)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Russian Twist',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.8 },
      { muscle: 'Hip Flexors', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Windshield Wipers',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.95 },
      { muscle: 'Latissimus Dorsi', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Pallof Press',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.85 },
      { muscle: 'Gluteus Medius', role: 'stabilizer', activationScore: 0.45 },
      { muscle: 'Anterior Deltoid', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    equipment: 'Other',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Latissimus Dorsi', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Pec Major (Sternocostal / Mid-Lower Chest)', role: 'secondary', activationScore: 0.4 },
      { muscle: 'Triceps Brachii (Long Head)', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 0.9 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Hip Flexors', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'V-Up',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.85 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Sit-Up',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 0.85 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.8 },
      { muscle: 'Obliques', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Bicycle Crunch',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.9 },
      { muscle: 'Hip Flexors', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Flutter Kicks',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.95 },
      { muscle: 'Core', role: 'primary', activationScore: 0.9 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 20,
    repRangeHigh: 30,
    createdAt: Date.now(),
  },
  {
    name: 'Toes-to-Bar',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.9 },
      { muscle: 'Latissimus Dorsi', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.55 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Mountain Climber',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 0.8 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.8 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 20,
    repRangeHigh: 30,
    createdAt: Date.now(),
  },
  {
    name: 'Bird Dog',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Erector Spinae', role: 'primary', activationScore: 0.85 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.8 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Posterior Deltoid', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hollow Body Hold',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Suitcase Carry',
    muscleGroup: 'Core',
    equipment: 'Dumbbell',
    movementPattern: 'carry',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 1 },
      { muscle: 'Forearm Flexors', role: 'primary', activationScore: 0.9 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Landmine 180 (Rotation)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary' },
      { muscle: 'Core (anti-rotation)', role: 'stabilizer' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Decline Sit-Up',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Other',
    targetMuscles: [
      { muscle: 'Rectus Abdominis (Upper)', role: 'primary' },
      { muscle: 'Hip Flexors', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Stir-the-Pot (Stability Ball Plank)',
    muscleGroup: 'Core',
    equipment: 'Other',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'primary', activationScore: 0.85 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Dragon Flag',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 0.85 },
      { muscle: 'Latissimus Dorsi', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'L-Sit',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Core', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Flexors', role: 'primary', activationScore: 1 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Plank with Shoulder Tap',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary', activationScore: 0.95 },
      { muscle: 'Core', role: 'primary', activationScore: 0.9 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 16,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
]
