import type { Exercise } from '@/types'

/**
 * Research-backed core exercise catalog. Grounded in EMG/ultrasound
 * literature: crunches preferentially activate the upper rectus abdominis
 * (~75% MVC) since the movement anchors at the pelvis; hanging leg raises
 * and reverse crunches activate the lower rectus abdominis and obliques
 * significantly more than crunches; plank variations with hollowing raise
 * oblique activation without changing rectus abdominis activation much.
 */
export const CORE_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Crunch (Floor)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Upper)', role: 'primary' }],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Crunch (Kneeling)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Upper)', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Crunch',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Upper)', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Weighted Sit-Up',
    muscleGroup: 'Core',
    muscleSubgroup: 'Upper Abs',
    equipment: 'Dumbbell',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Upper)', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Lower)', role: 'primary' }],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Knee Raise',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Lower)', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Crunch',
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Lower)', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: "Captain's Chair Leg Raise",
    muscleGroup: 'Core',
    muscleSubgroup: 'Lower Abs',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Rectus Abdominis (Lower)', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Plank (Forearm)',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Transverse Abdominis', role: 'primary' },
      { muscle: 'Rectus Abdominis (Upper)', role: 'secondary' },
      { muscle: 'Obliques', role: 'secondary' },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Side Plank',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Obliques', role: 'primary' }],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Woodchopper (High-to-Low)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Obliques', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Woodchopper (Low-to-High)',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Obliques', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Russian Twist',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary' },
      { muscle: 'Rectus Abdominis (Upper)', role: 'secondary' },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Hanging Windshield Wipers',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary' },
      { muscle: 'Rectus Abdominis (Lower)', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Pallof Press',
    muscleGroup: 'Core',
    muscleSubgroup: 'Obliques',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Obliques', role: 'primary' },
      { muscle: 'Transverse Abdominis', role: 'primary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    equipment: 'Other',
    targetMuscles: [
      { muscle: 'Rectus Abdominis (Upper)', role: 'primary' },
      { muscle: 'Transverse Abdominis', role: 'primary' },
      { muscle: 'Latissimus Dorsi', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Transverse Abdominis', role: 'primary' },
      { muscle: 'Rectus Abdominis (Lower)', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'V-Up',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Rectus Abdominis (Upper)', role: 'primary' },
      { muscle: 'Rectus Abdominis (Lower)', role: 'primary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
