import type { Exercise } from '@/types'

/**
 * Research-backed leg exercise catalog (quads/hamstrings/calves/adductors/
 * abductors — glute-dominant movements live in glutes.ts). Grounded in EMG
 * literature: conventional deadlifts hit the quads and erectors much harder
 * than Romanian deadlifts (~2x rectus femoris activation), while RDLs bias
 * the hamstrings (biceps femoris) over the erectors — an exception among
 * hip-hinge movements; leg press gives moderate hamstring activation at
 * deep knee flexion but far less than direct hamstring work. Belt squats
 * match back-squat quad activation while cutting lumbar erector load
 * roughly in half (hips carry the load, not the spine); stiff-leg deadlifts
 * differ from RDLs by keeping the knees nearly locked, biasing hamstring
 * stretch/erector involvement over glute drive; the Copenhagen plank is the
 * standout adductor isolation movement in the sports-med literature,
 * producing the highest adductor longus EMG among common adductor drills
 * while also loading the obliques heavily. Single-leg hip-hinge and
 * eccentric-stretch quad work round out the accessory pool: unilateral
 * RDLs drive markedly higher gluteus medius and biceps femoris activity
 * than their bilateral counterparts thanks to the balance demand, and the
 * reverse Nordic curl loads the quadriceps through a deep eccentric
 * stretch that concentric-only machine work can't replicate.
 */
export const LEGS_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Barbell',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.85 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.4 },
      { muscle: 'Gastrocnemius', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Front Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Barbell',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.75 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 0.95 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Leg Press',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.75 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Hamstrings', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hack Squat (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Walking Lunge (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'lunge',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 0.95 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.9 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Hamstrings', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Gluteus Medius', role: 'stabilizer', activationScore: 0.55 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'lunge',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.95 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Gluteus Medius', role: 'stabilizer', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Sumo Squat (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Adductors', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.9 },
      { muscle: 'Quadriceps', role: 'primary', activationScore: 0.85 },
      { muscle: 'Hamstrings', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Romanian Deadlift',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Barbell',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.95 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Dumbbell',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.95 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Forearm Flexors', role: 'stabilizer', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Lying Leg Curl (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gastrocnemius', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Leg Curl (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gastrocnemius', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Good Morning (Barbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Barbell',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Erector Spinae', role: 'primary', activationScore: 0.95 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.85 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Nordic Hamstring Curl',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Gastrocnemius', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Standing Calf Raise (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gastrocnemius', role: 'primary', activationScore: 1 },
      { muscle: 'Soleus', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Calf Raise (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Soleus', role: 'primary', activationScore: 1 },
      { muscle: 'Gastrocnemius', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Donkey Calf Raise',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gastrocnemius', role: 'primary', activationScore: 1 },
      { muscle: 'Soleus', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Hip Adduction',
    muscleGroup: 'Legs',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Adductors', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Hip Abduction',
    muscleGroup: 'Legs',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gluteus Medius', role: 'primary', activationScore: 1 },
      { muscle: 'Hip Abductors', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Sissy Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Bodyweight',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Soleus', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 8,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Pistol Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Bodyweight',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.9 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 5,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Belt Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.85 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Smith Machine Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.8 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Leg Press (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.8 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Gluteus Medius', role: 'stabilizer', activationScore: 0.45 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Lateral Lunge (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'lunge',
    targetMuscles: [
      { muscle: 'Adductors', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.85 },
      { muscle: 'Quadriceps', role: 'primary', activationScore: 0.8 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Stiff-Leg Deadlift (Barbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Barbell',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.9 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.8 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Glute-Ham Raise',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.85 },
      { muscle: 'Gastrocnemius', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Standing Leg Curl (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gastrocnemius', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Calf Press (Leg Press Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gastrocnemius', role: 'primary', activationScore: 1 },
      { muscle: 'Soleus', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Leg Calf Raise (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gastrocnemius', role: 'primary', activationScore: 1 },
      { muscle: 'Soleus', role: 'secondary', activationScore: 0.7 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hip Adduction Machine (Seated)',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Adductors', role: 'primary', activationScore: 1 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hip Abduction Machine (Seated)',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Gluteus Medius', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Copenhagen Plank',
    muscleGroup: 'Legs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Adductors', role: 'primary', activationScore: 1 },
      { muscle: 'Obliques', role: 'primary', activationScore: 0.85 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Leg Romanian Deadlift (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Dumbbell',
    movementPattern: 'hip_hinge',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.95 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Nordic Curl',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Box Squat (Barbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Barbell',
    movementPattern: 'squat',
    targetMuscles: [
      { muscle: 'Gluteus Maximus', role: 'primary', activationScore: 0.95 },
      { muscle: 'Quadriceps', role: 'primary', activationScore: 0.9 },
      { muscle: 'Hamstrings', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Adductors', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Step-Down',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    movementPattern: 'lunge',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Medius', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Wall Sit',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary', activationScore: 1 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Soleus', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 1,
    repRangeHigh: 3,
    createdAt: Date.now(),
  },
  {
    name: 'Tibialis Raise',
    muscleGroup: 'Legs',
    equipment: 'Bodyweight',
    movementPattern: 'isolation',
    targetMuscles: [{ muscle: 'Tibialis Anterior', role: 'primary', activationScore: 1 }],
    repRangeLow: 15,
    repRangeHigh: 25,
    createdAt: Date.now(),
  },
]
