import type { Exercise } from '@/types'

/**
 * Research-backed leg exercise catalog (quads/hamstrings/calves/adductors/
 * abductors — glute-dominant movements live in glutes.ts). Grounded in EMG
 * literature: conventional deadlifts hit the quads and erectors much harder
 * than Romanian deadlifts (~2x rectus femoris activation), while RDLs bias
 * the hamstrings (biceps femoris) over the erectors — an exception among
 * hip-hinge movements; leg press gives moderate hamstring activation at
 * deep knee flexion but far less than direct hamstring work.
 */
export const LEGS_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Erector Spinae', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Front Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Erector Spinae', role: 'secondary' },
      { muscle: 'Core', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Leg Press',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Hack Squat (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Quadriceps', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Walking Lunge (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'primary' },
      { muscle: 'Hamstrings', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'primary' },
      { muscle: 'Hamstrings', role: 'secondary' },
      { muscle: 'Adductors', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Sumo Squat (Dumbbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Quads',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Quadriceps', role: 'primary' },
      { muscle: 'Adductors', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Romanian Deadlift',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Erector Spinae', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
      { muscle: 'Erector Spinae', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Lying Leg Curl (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Hamstrings', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Leg Curl (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Hamstrings', role: 'primary' }],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Good Morning (Barbell)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Hamstrings', role: 'primary' },
      { muscle: 'Erector Spinae', role: 'primary' },
      { muscle: 'Gluteus Maximus', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Nordic Hamstring Curl',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Hamstrings',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Hamstrings', role: 'primary' }],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Standing Calf Raise (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Gastrocnemius', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Seated Calf Raise (Machine)',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Soleus', role: 'primary' }],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Donkey Calf Raise',
    muscleGroup: 'Legs',
    muscleSubgroup: 'Calves',
    equipment: 'Bodyweight',
    targetMuscles: [{ muscle: 'Gastrocnemius', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Hip Adduction',
    muscleGroup: 'Legs',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Adductors', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Hip Abduction',
    muscleGroup: 'Legs',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Hip Abductors', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
