import type { Exercise } from '@/types'

/**
 * Research-backed shoulder exercise catalog. Grounded in EMG literature:
 * pressing movements maximize anterior deltoid activation; lateral raises
 * (bent-arm especially) maximize lateral/middle deltoid; rear-delt-specific
 * work (rear raises, reverse flyes, face pulls) maximizes posterior deltoid,
 * which barely fires during pressing (~11% MVIC on overhead press vs ~24%
 * on lateral raise). Face pulls and scarecrows add external-rotation demand,
 * recruiting the rotator cuff (infraspinatus/teres minor) alongside the rear
 * delt; EMG on external-rotation exercises shows posterior deltoid EMG rises
 * with load while cuff activation stays comparatively load-insensitive, so
 * both are useful but train slightly different things. Behind-the-neck press
 * EMG shows it edges out front-loaded pressing for lateral and posterior
 * deltoid activation, which is why it's filed under Side Delts here rather
 * than Front Delts. Kettlebell and banded variants round out equipment
 * coverage: the kettlebell's offset center of mass adds an anti-tilt
 * stabilization demand pressing and presses lack, while bands impose a
 * strengthening (not descending) resistance curve that peaks at end-range
 * abduction rather than the mid-range peak of free weights.
 */
export const SHOULDERS_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Overhead Press (Standing)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.45 },
      { muscle: 'Serratus Anterior', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Shoulder Press (Seated)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Shoulder Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Machine',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.45 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Push Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Quadriceps', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Gluteus Maximus', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.45 },
    ],
    repRangeLow: 3,
    repRangeHigh: 5,
    createdAt: Date.now(),
  },
  {
    name: 'Pike Push-Up',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Bodyweight',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.35 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Landmine Shoulder Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.95 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.55 },
      { muscle: 'Serratus Anterior', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Front Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Trapezius (Upper)', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.45 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.35 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.35 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.25 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Upright Row',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_pull',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Trapezius (Upper)', role: 'primary', activationScore: 0.85 },
      { muscle: 'Biceps Brachii', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Upright Row',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    movementPattern: 'vertical_pull',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 0.95 },
      { muscle: 'Trapezius (Upper)', role: 'primary', activationScore: 0.8 },
      { muscle: 'Biceps Brachii', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cuban Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Dumbbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Rotator Cuff', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 0.8 },
      { muscle: 'Posterior Deltoid', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Bent-Over Rear Delt Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Erector Spinae', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Pec Deck (Machine)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Machine',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Rear Delt Fly',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Incline Y-Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary', activationScore: 1 },
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 0.85 },
      { muscle: 'Posterior Deltoid', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.5 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Z Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Core', role: 'primary', activationScore: 0.8 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Erector Spinae', role: 'secondary', activationScore: 0.6 },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Handstand Push-Up',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Bodyweight',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'primary', activationScore: 0.85 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.75 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.55 },
    ],
    repRangeLow: 5,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Behind-the-Neck Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Barbell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 0.85 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Lean-Away Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.35 },
      { muscle: 'Trapezius (Upper)', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Chest-Supported Dumbbell Reverse Fly',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Scarecrow (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Rotator Cuff', role: 'primary', activationScore: 1 },
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 0.8 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'W-Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 0.9 },
      { muscle: 'Rotator Cuff', role: 'primary', activationScore: 0.85 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary', activationScore: 0.7 },
      { muscle: 'Rhomboids', role: 'secondary', activationScore: 0.65 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Wide-Grip Rear Delt Row (Cable)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Cable',
    movementPattern: 'horizontal_pull',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary', activationScore: 0.85 },
      { muscle: 'Rhomboids', role: 'primary', activationScore: 0.8 },
      { muscle: 'Biceps Brachii', role: 'secondary', activationScore: 0.5 },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Single-Arm Cable Front Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Cable',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Trapezius (Upper)', role: 'stabilizer', activationScore: 0.3 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Kettlebell Shoulder Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Kettlebell',
    movementPattern: 'vertical_push',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Triceps Brachii', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'stabilizer', activationScore: 0.45 },
      { muscle: 'Rotator Cuff', role: 'stabilizer', activationScore: 0.4 },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Plate Front Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Other',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Pec Major (Clavicular / Upper Chest)', role: 'secondary', activationScore: 0.5 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.35 },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Resistance Band Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Bands',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary', activationScore: 1 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.4 },
    ],
    repRangeLow: 15,
    repRangeHigh: 20,
    createdAt: Date.now(),
  },
  {
    name: 'Kettlebell Halo',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Kettlebell',
    movementPattern: 'isolation',
    targetMuscles: [
      { muscle: 'Rotator Cuff', role: 'primary', activationScore: 0.95 },
      { muscle: 'Anterior Deltoid', role: 'secondary', activationScore: 0.65 },
      { muscle: 'Lateral Deltoid', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Core', role: 'secondary', activationScore: 0.6 },
      { muscle: 'Trapezius (Upper)', role: 'secondary', activationScore: 0.55 },
    ],
    repRangeLow: 8,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
]
