import type { Exercise } from '@/types'

/**
 * Research-backed shoulder exercise catalog. Grounded in EMG literature:
 * pressing movements maximize anterior deltoid activation; lateral raises
 * (bent-arm especially) maximize lateral/middle deltoid; rear-delt-specific
 * work (rear raises, reverse flyes, face pulls) maximizes posterior deltoid,
 * which barely fires during pressing (~11% MVIC on overhead press vs ~24%
 * on lateral raise). Face pulls and scarecrows add external-rotation demand,
 * recruiting the rotator cuff (infraspinatus/teres minor) alongside the rear
 * delt; EMG on external-rotation exercises shows posterior deltoid EMG rises
 * with load while cuff activation stays comparatively load-insensitive, so
 * both are useful but train slightly different things. Behind-the-neck press
 * EMG shows it edges out front-loaded pressing for lateral and posterior
 * deltoid activation, which is why it's filed under Side Delts here rather
 * than Front Delts.
 */
export const SHOULDERS_EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    name: 'Barbell Overhead Press (Standing)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Shoulder Press (Seated)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Lateral Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Shoulder Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Lateral Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Push Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
      { muscle: 'Quadriceps', role: 'secondary' },
    ],
    repRangeLow: 3,
    repRangeHigh: 5,
    createdAt: Date.now(),
  },
  {
    name: 'Pike Push-Up',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Landmine Shoulder Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Triceps Brachii (Lateral Head)', role: 'secondary' },
      { muscle: 'Core (anti-rotation)', role: 'secondary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Front Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Dumbbell',
    targetMuscles: [{ muscle: 'Anterior Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Dumbbell',
    targetMuscles: [{ muscle: 'Lateral Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Lateral Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Machine Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Machine',
    targetMuscles: [{ muscle: 'Lateral Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Barbell Upright Row',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Upper)', role: 'primary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Upright Row',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Upper)', role: 'primary' },
    ],
    repRangeLow: 8,
    repRangeHigh: 12,
    createdAt: Date.now(),
  },
  {
    name: 'Cuban Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'stabilizer' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Bent-Over Rear Delt Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Reverse Pec Deck (Machine)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Machine',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Cable Rear Delt Fly',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Posterior Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Incline Y-Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Trapezius (Mid/Lower)', role: 'primary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Z Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Lateral Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Core', role: 'stabilizer' },
    ],
    repRangeLow: 5,
    repRangeHigh: 8,
    createdAt: Date.now(),
  },
  {
    name: 'Handstand Push-Up',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Front Delts',
    equipment: 'Bodyweight',
    targetMuscles: [
      { muscle: 'Anterior Deltoid', role: 'primary' },
      { muscle: 'Lateral Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
    ],
    repRangeLow: 5,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Behind-the-Neck Press',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Barbell',
    targetMuscles: [
      { muscle: 'Lateral Deltoid', role: 'primary' },
      { muscle: 'Posterior Deltoid', role: 'secondary' },
      { muscle: 'Triceps Brachii', role: 'secondary' },
      { muscle: 'Trapezius (Upper)', role: 'secondary' },
    ],
    repRangeLow: 6,
    repRangeHigh: 10,
    createdAt: Date.now(),
  },
  {
    name: 'Lean-Away Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Side Delts',
    equipment: 'Cable',
    targetMuscles: [{ muscle: 'Lateral Deltoid', role: 'primary' }],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Chest-Supported Dumbbell Reverse Fly',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
      { muscle: 'Rhomboids', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Scarecrow (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Rotator Cuff', role: 'primary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'W-Raise (Dumbbell)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Dumbbell',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
      { muscle: 'Rotator Cuff', role: 'secondary' },
    ],
    repRangeLow: 12,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
  {
    name: 'Wide-Grip Rear Delt Row (Cable)',
    muscleGroup: 'Shoulders',
    muscleSubgroup: 'Rear Delts',
    equipment: 'Cable',
    targetMuscles: [
      { muscle: 'Posterior Deltoid', role: 'primary' },
      { muscle: 'Rhomboids', role: 'secondary' },
      { muscle: 'Trapezius (Mid/Lower)', role: 'secondary' },
    ],
    repRangeLow: 10,
    repRangeHigh: 15,
    createdAt: Date.now(),
  },
]
